apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-pod
  name: cm-pod
spec:
  containers:
  - image: nginx
    name: cm-pod
    env:
      # Define the environment variable
      - name: APP_MODE
        valueFrom:
          configMapKeyRef:
            # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
            name: app-config
            # Specify the key associated with the value
            key: APP_MODE
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---