apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: nginx
    name: secret-pod
    envFrom:
    - secretRef:
        name: db-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always