apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: db-secret
  containers:
  - image: nginx
    name: secret-pod
    volumeMounts:
      # name must match the volume name below
      - name: secret-volume
        mountPath: /etc/secret
        readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always