apiVersion: v1
kind: Pod
metadata:
  labels:
    run: probe-pod
  name: probe-pod
spec:
  containers:
  - image: nginx
    name: probe-pod
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 15
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}