apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: limit
spec: {}
status: {}
----
apiVersion: v1
kind: Pod
metadata:
  namespace: limit
  labels:
    run: resource-checker
  name: resource-checker
spec:
  containers:
  - image: httpd:alpine
    name: my-container
    resources:
      requests:
        memory: 30Mi
        cpu: 30m
      limits:
        memory: 300Mi
        cpu: 300m
  dnsPolicy: ClusterFirst
  restartPolicy: Always