apiVersion: v1
kind: Pod
metadata:
  labels:
    run: podenv3
  name: podenv3
spec:
  containers:
  - command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - configMapRef:
        name: cm1
    image: busybox
    name: podenv3
  restartPolicy: Never

