apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: livess
  name: livess
spec:
  containers:
  - image: nginx
    name: livess
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
  restartPolicy: Always
status: {}